version: '3.8'
services:
  banking:
    build:
      context: .
      dockerfile: Dockerfile
    image: bankingapplication:latest
    ports: 
      - "8082:8082"
    restart: always

  prometheus:
    image: ubuntu/prometheus
    container_name: myprometheus
    ports:
     - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana
    container_name: mygrafana
    ports:
      - "3000:3000"
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: mycadvisor
    ports:
      - "8080:8080"
    restart: always
